In [1]:
from __future__ import annotations
import typing
from dataclasses import dataclass, field
import warnings
from contextlib import contextmanager
import itertools

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
N = 4
x = np.array([-1, 1, 2, 4, 5])
f = np.array([46, 24, 4, -54, -20])

In [14]:
result: np.ndarray['N'] = np.zeros(N + 1, dtype="float64")

for i in range(N):
    L_i: np.ndarray['N'] = np.poly(x[np.arange(N + 1) != i])
    print(L_i, np.polyval(L_i, x[i]))
    L_i /= np.polyval(L_i, x[i])

    result += f[i] * L_i

result

[  1. -12.  49. -78.  40.] 180.0
[  1. -10.  27.  -2. -40.] -24.0
[  1.  -9.  19.   9. -20.] 18.0
[  1.  -7.   9.   7. -10.] -30.0


array([ 1.27777778, -7.66666667,  5.94444444, -3.33333333, 27.77777778])

In [17]:
np.polyval(result, 3)

-32.22222222222224